experiment:
  name: infogan_dcgan_concatmetos_nofilm_64_spr_largedisonly_10_largemetos_10k_eadam
  exp_dir: /scratch/jassiene/clouds/experiments
  img_path: /scratch/jassiene/images/new_clouds.sif
  repeat: 10
runs:
  - sbatch:
      runtime: "20:00:00"
      message: infogan_dcgan_concatmetos_nofilm_64_spr_largedisonly_10_largemetos_10k_eadam
      conf_name: gan_weights
      cpu: 8
      gpu: "gpu:1"
      no_comet: false
      mem: "32GB"
    config:
      model:
        disc_size: 64
        n_blocks: 5
      data:
        path: "/scratch/jassiene/data/low_clouds/full_dataset"
        with_stats: true
        noq: false
        load_limit: 10000
      val:
        infer_every: 100 # How often to infer validation images
        nb_of_inferences: 3 # no of inferences (generated imgs) per validation sample (input + real_img)
      train:
        batch_size: 780
        num_D_accumulations: 1
        n_epochs: 10001
        num_workers: 12
        n_in_mem: 8
        with_stats: true
        save_every: 500
        infer_every: 100
        optimizer: "extraadam"
        feature_extractor_loss: false
        lambda_gan: 1 # Gan loss scaling constant
        lambda_L: # Matching loss scaling constant
          sample: list
          from: [1, 2, 3, 4, 5]
        lambda_infogan: # Mutual Information loss scaling constant
          sample: list
          from: [4, 5]
        lambda_metos: # Mutual Information loss scaling constant
          sample: list
          from: [4, 5]
        lr_d:
          sample: list
          from: [0.01, 0.001, 0.0001, 0.00001]
        lr_g:
          sample: list
          from: [0.1, 0.01, 0.001, 0.0001]
